# app/services/enhanced_keyword_classifier.py
"""
Enhanced keyword classifier covering all 20 editorial domains + geography detection.

Used as a robust fallback when ALL LLM classification attempts fail (<1% of the time).
This classifier is a legitimate classification engine — not a minimal stub.
Each domain has 30-50 keywords. Geography detection uses US state/city names and
international country/organization keywords.
"""

import re

from app.models import Domain

# ---------------------------------------------------------------------------
# Domain keyword sets (30-50 keywords each)
# ---------------------------------------------------------------------------

DOMAIN_KEYWORDS: dict[str, set[str]] = {
    Domain.GLOBAL_AFFAIRS: {
        "united nations",
        "un",
        "nato",
        "g7",
        "g20",
        "european union",
        "eu",
        "world bank",
        "imf",
        "international",
        "foreign policy",
        "diplomatic",
        "embassy",
        "ambassador",
        "treaty",
        "summit",
        "sanctions",
        "geopolitical",
        "refugee",
        "humanitarian",
        "peacekeeping",
        "foreign minister",
        "bilateral",
        "multilateral",
        "sovereignty",
        "territorial",
        "global",
        "transnational",
        "cross-border",
        "world leaders",
        "diplomacy",
        "coalition",
        "alliance",
        "trade agreement",
        "tariff",
    },
    Domain.GOVERNANCE_POLITICS: {
        "congress",
        "senate",
        "house of representatives",
        "parliament",
        "president",
        "prime minister",
        "governor",
        "legislation",
        "bill",
        "law",
        "executive order",
        "veto",
        "bipartisan",
        "partisan",
        "democrat",
        "republican",
        "gop",
        "election",
        "vote",
        "ballot",
        "campaign",
        "caucus",
        "primary",
        "midterm",
        "inauguration",
        "constitutional",
        "amendment",
        "filibuster",
        "impeachment",
        "political",
        "politician",
        "policymaker",
        "regulation",
        "policy",
        "white house",
        "capitol",
        "state legislature",
        "city council",
        "mayor",
        "alderman",
        "commissioner",
        "government",
    },
    Domain.LAW_JUSTICE: {
        "supreme court",
        "court",
        "judge",
        "justice",
        "ruling",
        "verdict",
        "lawsuit",
        "litigation",
        "plaintiff",
        "defendant",
        "prosecutor",
        "attorney",
        "lawyer",
        "legal",
        "judicial",
        "trial",
        "jury",
        "indictment",
        "conviction",
        "sentencing",
        "appeal",
        "precedent",
        "constitutional",
        "civil rights",
        "civil liberties",
        "due process",
        "habeas corpus",
        "injunction",
        "statute",
        "ordinance",
        "legal challenge",
        "class action",
        "settlement",
        "arbitration",
        "doj",
        "department of justice",
        "federal court",
        "district court",
    },
    Domain.SECURITY_DEFENSE: {
        "military",
        "army",
        "navy",
        "air force",
        "marines",
        "pentagon",
        "defense",
        "defense department",
        "national security",
        "intelligence",
        "cia",
        "nsa",
        "fbi",
        "homeland security",
        "dhs",
        "counterterrorism",
        "missile",
        "nuclear",
        "weapons",
        "armed forces",
        "troops",
        "deployment",
        "drone",
        "airstrikes",
        "warfare",
        "combat",
        "veteran",
        "military base",
        "joint chiefs",
        "special forces",
        "cybersecurity",
        "espionage",
        "surveillance",
        "threat assessment",
        "defense spending",
        "arms deal",
        "munitions",
    },
    Domain.CRIME_PUBLIC_SAFETY: {
        "police",
        "arrest",
        "crime",
        "criminal",
        "murder",
        "homicide",
        "shooting",
        "robbery",
        "theft",
        "burglary",
        "assault",
        "fraud",
        "scam",
        "drug",
        "trafficking",
        "gang",
        "cartel",
        "investigation",
        "detective",
        "suspect",
        "victim",
        "witness",
        "prison",
        "jail",
        "incarceration",
        "parole",
        "probation",
        "bail",
        "warrant",
        "forensic",
        "evidence",
        "crime scene",
        "law enforcement",
        "sheriff",
        "public safety",
        "homelessness",
        "domestic violence",
        "missing person",
        "kidnapping",
        "arson",
        "vandalism",
    },
    Domain.ECONOMY_MACROECONOMICS: {
        "economy",
        "economic",
        "gdp",
        "inflation",
        "deflation",
        "recession",
        "recovery",
        "growth",
        "federal reserve",
        "fed",
        "interest rate",
        "monetary policy",
        "fiscal policy",
        "stimulus",
        "debt",
        "deficit",
        "budget",
        "spending",
        "austerity",
        "unemployment",
        "jobs report",
        "labor market",
        "consumer spending",
        "consumer confidence",
        "cpi",
        "ppi",
        "economic indicator",
        "trade deficit",
        "trade surplus",
        "national debt",
        "treasury",
        "bond",
        "yield curve",
        "quantitative easing",
        "central bank",
        "macroeconomic",
    },
    Domain.FINANCE_MARKETS: {
        "stock",
        "market",
        "dow",
        "nasdaq",
        "s&p",
        "wall street",
        "investor",
        "trading",
        "shares",
        "ipo",
        "earnings",
        "dividend",
        "portfolio",
        "hedge fund",
        "mutual fund",
        "etf",
        "index fund",
        "bull market",
        "bear market",
        "rally",
        "sell-off",
        "correction",
        "cryptocurrency",
        "bitcoin",
        "crypto",
        "blockchain",
        "defi",
        "fintech",
        "banking",
        "bank",
        "investment",
        "venture capital",
        "private equity",
        "asset management",
        "wealth management",
        "securities",
        "sec",
        "exchange",
        "forex",
        "commodities",
    },
    Domain.BUSINESS_INDUSTRY: {
        "company",
        "corporate",
        "ceo",
        "merger",
        "acquisition",
        "revenue",
        "profit",
        "startup",
        "entrepreneur",
        "business",
        "industry",
        "manufacturing",
        "supply chain",
        "logistics",
        "retail",
        "e-commerce",
        "brand",
        "marketing",
        "advertising",
        "sales",
        "quarter",
        "annual report",
        "board of directors",
        "shareholder",
        "valuation",
        "bankruptcy",
        "restructuring",
        "layoffs",
        "hiring",
        "expansion",
        "franchise",
        "conglomerate",
        "subsidiary",
        "spinoff",
        "small business",
        "enterprise",
        "b2b",
        "consumer goods",
    },
    Domain.LABOR_DEMOGRAPHICS: {
        "workers",
        "labor",
        "union",
        "strike",
        "wages",
        "minimum wage",
        "gig economy",
        "freelance",
        "remote work",
        "workplace",
        "employment",
        "hiring",
        "layoff",
        "workforce",
        "pension",
        "retirement",
        "social security",
        "benefits",
        "immigration",
        "migration",
        "population",
        "census",
        "demographic",
        "birth rate",
        "aging",
        "generation",
        "diversity",
        "equity",
        "inclusion",
        "gender pay gap",
        "occupational safety",
        "osha",
        "labor department",
        "collective bargaining",
        "right to work",
        "worker rights",
    },
    Domain.INFRASTRUCTURE_SYSTEMS: {
        "infrastructure",
        "highway",
        "bridge",
        "road",
        "railroad",
        "transit",
        "airport",
        "port",
        "dam",
        "water system",
        "sewage",
        "broadband",
        "internet access",
        "power grid",
        "electrical grid",
        "pipeline",
        "construction",
        "engineering",
        "urban planning",
        "zoning",
        "public transit",
        "subway",
        "bus",
        "transportation",
        "commute",
        "housing",
        "affordable housing",
        "real estate",
        "development",
        "smart city",
        "telecom",
        "telecommunications",
        "5g",
        "public works",
        "infrastructure bill",
    },
    Domain.ENERGY: {
        "energy",
        "oil",
        "gas",
        "natural gas",
        "petroleum",
        "opec",
        "solar",
        "wind",
        "renewable",
        "clean energy",
        "fossil fuel",
        "nuclear energy",
        "nuclear power",
        "coal",
        "fracking",
        "drilling",
        "refinery",
        "power plant",
        "electricity",
        "utility",
        "energy transition",
        "carbon",
        "emissions",
        "net zero",
        "hydrogen",
        "biofuel",
        "geothermal",
        "hydroelectric",
        "battery",
        "energy storage",
        "ev",
        "electric vehicle",
        "energy policy",
        "energy crisis",
        "blackout",
        "power outage",
    },
    Domain.ENVIRONMENT_CLIMATE: {
        "climate",
        "climate change",
        "global warming",
        "environment",
        "environmental",
        "pollution",
        "air quality",
        "water quality",
        "deforestation",
        "biodiversity",
        "conservation",
        "wildlife",
        "endangered species",
        "ecosystem",
        "habitat",
        "sustainability",
        "carbon footprint",
        "greenhouse gas",
        "paris agreement",
        "epa",
        "environmental protection",
        "recycling",
        "waste",
        "plastic",
        "ocean",
        "coral reef",
        "arctic",
        "glacier",
        "ice cap",
        "drought",
        "wildfire",
        "flooding",
        "erosion",
        "wetland",
        "national park",
        "clean water",
        "toxic",
        "contamination",
    },
    Domain.SCIENCE_RESEARCH: {
        "science",
        "research",
        "study",
        "scientist",
        "researcher",
        "discovery",
        "experiment",
        "laboratory",
        "academic",
        "journal",
        "peer review",
        "nasa",
        "space",
        "astronomy",
        "astrophysics",
        "physics",
        "chemistry",
        "biology",
        "genetics",
        "genome",
        "dna",
        "evolution",
        "fossil",
        "paleontology",
        "archaeology",
        "quantum",
        "particle",
        "cern",
        "telescope",
        "satellite",
        "mars",
        "moon",
        "asteroid",
        "rocket",
        "spacex",
        "scientific",
        "breakthrough",
        "innovation",
        "nobel prize",
    },
    Domain.HEALTH_MEDICINE: {
        "health",
        "medical",
        "medicine",
        "doctor",
        "hospital",
        "patient",
        "disease",
        "virus",
        "pandemic",
        "epidemic",
        "vaccine",
        "vaccination",
        "fda",
        "cdc",
        "who",
        "public health",
        "mental health",
        "cancer",
        "diabetes",
        "heart disease",
        "alzheimer",
        "dementia",
        "obesity",
        "drug",
        "pharmaceutical",
        "clinical trial",
        "therapy",
        "treatment",
        "surgery",
        "diagnosis",
        "symptom",
        "prevention",
        "wellness",
        "healthcare",
        "insurance",
        "medicare",
        "medicaid",
        "opioid",
        "addiction",
        "nutrition",
        "fitness",
        "mortality",
        "life expectancy",
    },
    Domain.TECHNOLOGY: {
        "ai",
        "artificial intelligence",
        "machine learning",
        "algorithm",
        "software",
        "hardware",
        "app",
        "smartphone",
        "iphone",
        "android",
        "internet",
        "cyber",
        "hacker",
        "data breach",
        "privacy",
        "tech",
        "technology",
        "silicon valley",
        "cloud",
        "computing",
        "chip",
        "semiconductor",
        "processor",
        "nvidia",
        "openai",
        "anthropic",
        "google",
        "microsoft",
        "apple",
        "meta",
        "amazon",
        "robot",
        "automation",
        "self-driving",
        "autonomous",
        "virtual reality",
        "augmented reality",
        "metaverse",
        "quantum computing",
        "big data",
        "data science",
        "saas",
        "startup",
        "venture",
        "tesla",
        "spacex",
    },
    Domain.MEDIA_INFORMATION: {
        "media",
        "journalism",
        "news",
        "newspaper",
        "broadcast",
        "social media",
        "facebook",
        "twitter",
        "instagram",
        "tiktok",
        "youtube",
        "podcast",
        "streaming",
        "content",
        "misinformation",
        "disinformation",
        "fake news",
        "fact check",
        "censorship",
        "free press",
        "first amendment",
        "content moderation",
        "platform",
        "publisher",
        "editor",
        "reporter",
        "journalist",
        "propaganda",
        "influence",
        "viral",
        "algorithm",
        "media company",
        "network",
        "cable news",
        "press freedom",
    },
    Domain.SPORTS_COMPETITION: {
        "sports",
        "football",
        "nfl",
        "basketball",
        "nba",
        "baseball",
        "mlb",
        "soccer",
        "hockey",
        "nhl",
        "tennis",
        "golf",
        "olympics",
        "athlete",
        "championship",
        "playoff",
        "super bowl",
        "world cup",
        "world series",
        "draft",
        "trade",
        "free agent",
        "coach",
        "manager",
        "referee",
        "stadium",
        "arena",
        "tournament",
        "league",
        "season",
        "game",
        "match",
        "score",
        "win",
        "loss",
        "record",
        "mvp",
        "hall of fame",
        "ncaa",
        "college football",
        "college basketball",
        "cricket",
        "rugby",
        "boxing",
        "mma",
        "ufc",
        "formula 1",
        "f1",
        "nascar",
        "espn",
        "fifa",
    },
    Domain.SOCIETY_CULTURE: {
        "culture",
        "society",
        "social",
        "community",
        "civil rights",
        "race",
        "racism",
        "discrimination",
        "equality",
        "justice",
        "protest",
        "activism",
        "movement",
        "religion",
        "church",
        "faith",
        "education",
        "school",
        "university",
        "college",
        "student",
        "teacher",
        "curriculum",
        "art",
        "music",
        "film",
        "movie",
        "theater",
        "museum",
        "literature",
        "book",
        "festival",
        "tradition",
        "heritage",
        "identity",
        "lgbtq",
        "gender",
        "feminism",
        "philanthropy",
        "charity",
        "nonprofit",
    },
    Domain.LIFESTYLE_PERSONAL: {
        "lifestyle",
        "celebrity",
        "entertainment",
        "fashion",
        "style",
        "food",
        "restaurant",
        "cooking",
        "recipe",
        "travel",
        "tourism",
        "hotel",
        "vacation",
        "holiday",
        "wellness",
        "beauty",
        "skincare",
        "fitness",
        "yoga",
        "meditation",
        "home",
        "decor",
        "interior",
        "garden",
        "pet",
        "parenting",
        "family",
        "relationship",
        "dating",
        "wedding",
        "real estate",
        "personal finance",
        "shopping",
        "tech gadget",
        "review",
        "best of",
        "how to",
        "tips",
        "advice",
        "trend",
        "influencer",
        "viral",
    },
    Domain.INCIDENTS_DISASTERS: {
        "disaster",
        "earthquake",
        "hurricane",
        "tornado",
        "flood",
        "wildfire",
        "tsunami",
        "volcano",
        "avalanche",
        "landslide",
        "explosion",
        "collapse",
        "crash",
        "accident",
        "derailment",
        "fire",
        "emergency",
        "evacuation",
        "rescue",
        "casualty",
        "fatality",
        "injury",
        "damage",
        "destruction",
        "devastation",
        "relief",
        "aid",
        "fema",
        "red cross",
        "natural disaster",
        "weather",
        "storm",
        "blizzard",
        "heat wave",
        "cold snap",
        "power outage",
        "blackout",
        "state of emergency",
        "mass shooting",
        "attack",
        "bombing",
        "incident",
    },
}


# ---------------------------------------------------------------------------
# Geography detection keywords
# ---------------------------------------------------------------------------

# US state names and abbreviations
US_KEYWORDS: set[str] = {
    "united states",
    "u.s.",
    "usa",
    "american",
    "alabama",
    "alaska",
    "arizona",
    "arkansas",
    "california",
    "colorado",
    "connecticut",
    "delaware",
    "florida",
    "georgia",
    "hawaii",
    "idaho",
    "illinois",
    "indiana",
    "iowa",
    "kansas",
    "kentucky",
    "louisiana",
    "maine",
    "maryland",
    "massachusetts",
    "michigan",
    "minnesota",
    "mississippi",
    "missouri",
    "montana",
    "nebraska",
    "nevada",
    "new hampshire",
    "new jersey",
    "new mexico",
    "new york",
    "north carolina",
    "north dakota",
    "ohio",
    "oklahoma",
    "oregon",
    "pennsylvania",
    "rhode island",
    "south carolina",
    "south dakota",
    "tennessee",
    "texas",
    "utah",
    "vermont",
    "virginia",
    "washington",
    "west virginia",
    "wisconsin",
    "wyoming",
    "district of columbia",
    "d.c.",
    # Major US cities
    "los angeles",
    "chicago",
    "houston",
    "phoenix",
    "philadelphia",
    "san antonio",
    "san diego",
    "dallas",
    "san jose",
    "austin",
    "seattle",
    "denver",
    "boston",
    "detroit",
    "nashville",
    "portland",
    "las vegas",
    "atlanta",
    "miami",
    "minneapolis",
    "san francisco",
    # US government/institutions
    "congress",
    "senate",
    "white house",
    "pentagon",
    "fbi",
    "cia",
    "federal",
    "supreme court",
    "capitol hill",
}

# Local indicators (city-level, county, neighborhood)
LOCAL_KEYWORDS: set[str] = {
    "mayor",
    "city council",
    "county",
    "municipal",
    "neighborhood",
    "community",
    "residents",
    "local",
    "school board",
    "zoning",
    "traffic",
    "public transit",
    "town",
    "village",
    "district",
    "township",
    "borough",
    "precinct",
    "ward",
}

# International indicators
INTERNATIONAL_KEYWORDS: set[str] = {
    "china",
    "russia",
    "ukraine",
    "europe",
    "asia",
    "africa",
    "middle east",
    "israel",
    "gaza",
    "palestine",
    "iran",
    "north korea",
    "india",
    "japan",
    "uk",
    "britain",
    "france",
    "germany",
    "italy",
    "spain",
    "brazil",
    "australia",
    "canada",
    "mexico",
    "south korea",
    "taiwan",
    "hong kong",
    "saudi arabia",
    "turkey",
    "egypt",
    "nigeria",
    "south africa",
    "indonesia",
    "pakistan",
    "bangladesh",
    "vietnam",
    "thailand",
    "philippines",
    "colombia",
    "argentina",
    "chile",
    "nato",
    "united nations",
    "un",
    "european union",
    "eu",
    "world bank",
    "imf",
    "opec",
    "brics",
    "foreign",
    "overseas",
    "abroad",
    "international",
}

# Source slug hints for geography
SOURCE_GEO_HINTS: dict[str, str] = {
    "ap-world": "international",
    "reuters-world": "international",
    "bbc-world": "international",
    "ap-us": "us",
    "ap-local": "local",
}


def _score_text(text: str, keywords: set[str], title_weight: int = 1) -> int:
    """Score text against a keyword set."""
    text_lower = text.lower()
    score = 0
    for keyword in keywords:
        pattern = r"\b" + re.escape(keyword) + r"\b"
        if re.search(pattern, text_lower):
            score += title_weight
    return score


def detect_geography(
    title: str,
    description: str | None = None,
    body_excerpt: str | None = None,
    source_slug: str | None = None,
) -> str:
    """
    Detect article geography: 'us', 'local', 'international', or 'mixed'.

    Args:
        title: Article title
        description: Article description
        body_excerpt: First ~2000 chars of body
        source_slug: Source identifier for hints

    Returns:
        Geography string
    """
    # Check source hint first
    if source_slug and source_slug in SOURCE_GEO_HINTS:
        return SOURCE_GEO_HINTS[source_slug]

    # Score each geography
    title_text = title or ""
    desc_text = description or ""
    body_text = (body_excerpt or "")[:2000]

    us_score = _score_text(title_text, US_KEYWORDS, 3)
    us_score += _score_text(desc_text + " " + body_text, US_KEYWORDS, 1)

    local_score = _score_text(title_text, LOCAL_KEYWORDS, 3)
    local_score += _score_text(desc_text + " " + body_text, LOCAL_KEYWORDS, 1)

    intl_score = _score_text(title_text, INTERNATIONAL_KEYWORDS, 3)
    intl_score += _score_text(desc_text + " " + body_text, INTERNATIONAL_KEYWORDS, 1)

    # Determine geography
    if local_score > 0 and local_score >= us_score and local_score >= intl_score:
        return "local"
    if intl_score > us_score and intl_score > 0:
        return "international"
    if us_score > 0:
        return "us"
    if intl_score > 0:
        return "international"

    # Default to US for US-centric news sources
    return "us"


def classify_by_keywords(
    title: str,
    description: str | None = None,
    body_excerpt: str | None = None,
    source_slug: str | None = None,
) -> dict:
    """
    Classify an article into one of 20 domains using keyword heuristics.

    Args:
        title: Article title
        description: Article description
        body_excerpt: First ~2000 chars of body
        source_slug: Source identifier

    Returns:
        dict with keys: domain, geography, tags
    """
    title_text = title or ""
    desc_text = description or ""
    body_text = (body_excerpt or "")[:2000]
    combined = desc_text + " " + body_text

    # Score each domain
    scores: dict[str, int] = {}
    for domain_val, keywords in DOMAIN_KEYWORDS.items():
        # Title keywords are worth 3x
        score = _score_text(title_text, keywords, 3)
        score += _score_text(combined, keywords, 1)
        scores[domain_val] = score

    # Find best domain
    best_domain = max(scores, key=lambda d: scores[d])
    best_score = scores[best_domain]

    # Default to global_affairs if no keywords match
    if best_score == 0:
        best_domain = Domain.GLOBAL_AFFAIRS

    # Detect geography
    geography = detect_geography(title_text, desc_text, body_text, source_slug)

    return {
        "domain": best_domain if isinstance(best_domain, str) else best_domain.value,
        "geography": geography,
        "tags": {
            "geography": geography,
            "geography_detail": geography,
            "actors": [],
            "action_type": "general",
            "topic_keywords": [],
        },
    }
