"""add neutrality scoring fields

Revision ID: 48b2882dfa37
Revises: 4b0a5b86cbe8
Create Date: 2025-12-10 21:20:16.990615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b2882dfa37'
down_revision: Union[str, Sequence[str], None] = '4b0a5b86cbe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_summaries', sa.Column('neutrality_score', sa.Integer(), nullable=True))
    op.add_column('article_summaries', sa.Column('bias_terms', sa.JSON(), nullable=True))
    op.add_column('article_summaries', sa.Column('reading_level', sa.Integer(), nullable=True))
    op.add_column('article_summaries', sa.Column('political_lean', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_summaries', 'political_lean')
    op.drop_column('article_summaries', 'reading_level')
    op.drop_column('article_summaries', 'bias_terms')
    op.drop_column('article_summaries', 'neutrality_score')
    # ### end Alembic commands ###
