"""initial schema

Revision ID: 4b0a5b86cbe8
Revises: 
Create Date: 2025-12-09 22:23:08.078965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0a5b86cbe8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('api_identifier', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('system_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version_tag', sa.String(length=64), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=True),
    sa.Column('original_title', sa.Text(), nullable=False),
    sa.Column('original_description', sa.Text(), nullable=True),
    sa.Column('original_body', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_raw_id', sa.UUID(), nullable=False),
    sa.Column('version_tag', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('neutral_title', sa.Text(), nullable=False),
    sa.Column('neutral_summary_short', sa.Text(), nullable=False),
    sa.Column('neutral_summary_extended', sa.Text(), nullable=True),
    sa.Column('tone_flag', sa.Boolean(), nullable=False),
    sa.Column('tone_issues', sa.JSON(), nullable=True),
    sa.Column('misinfo_flag', sa.Boolean(), nullable=False),
    sa.Column('misinfo_notes', sa.JSON(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['article_raw_id'], ['articles_raw.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster_articles',
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('article_raw_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_raw_id'], ['articles_raw.id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['article_clusters.id'], ),
    sa.PrimaryKeyConstraint('cluster_id', 'article_raw_id')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_raw_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['article_raw_id'], ['articles_raw.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_runs')
    op.drop_table('cluster_articles')
    op.drop_table('article_summaries')
    op.drop_table('articles_raw')
    op.drop_table('system_prompts')
    op.drop_table('sources')
    op.drop_table('article_clusters')
    # ### end Alembic commands ###
