"""add bias_spans to article_summaries

Revision ID: 4eb5c6286d76
Revises: 48b2882dfa37
Create Date: 2025-12-11 21:30:12.559589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb5c6286d76'
down_revision: Union[str, Sequence[str], None] = '48b2882dfa37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_summaries', sa.Column('bias_spans', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_summaries', 'bias_spans')
    # ### end Alembic commands ###
