"""add_pipeline_observability

Revision ID: 53b582a6786a
Revises: 006_add_manipulation_spans
Create Date: 2026-01-25 00:27:34.890664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53b582a6786a'
down_revision: Union[str, Sequence[str], None] = '006_add_manipulation_spans'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_run_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('ingest_total', sa.Integer(), nullable=False),
    sa.Column('ingest_success', sa.Integer(), nullable=False),
    sa.Column('ingest_body_downloaded', sa.Integer(), nullable=False),
    sa.Column('ingest_body_failed', sa.Integer(), nullable=False),
    sa.Column('ingest_skipped_duplicate', sa.Integer(), nullable=False),
    sa.Column('neutralize_total', sa.Integer(), nullable=False),
    sa.Column('neutralize_success', sa.Integer(), nullable=False),
    sa.Column('neutralize_skipped_no_body', sa.Integer(), nullable=False),
    sa.Column('neutralize_failed', sa.Integer(), nullable=False),
    sa.Column('brief_story_count', sa.Integer(), nullable=False),
    sa.Column('brief_section_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('alerts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_run_summaries_finished_at', 'pipeline_run_summaries', ['finished_at'], unique=False)
    op.create_index('ix_pipeline_run_summaries_status', 'pipeline_run_summaries', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_run_summaries_trace_id'), 'pipeline_run_summaries', ['trace_id'], unique=True)
    op.add_column('pipeline_logs', sa.Column('trace_id', sa.String(length=36), nullable=True))
    op.add_column('pipeline_logs', sa.Column('entry_url', sa.String(length=2048), nullable=True))
    op.add_column('pipeline_logs', sa.Column('entry_url_hash', sa.String(length=64), nullable=True))
    op.add_column('pipeline_logs', sa.Column('failure_reason', sa.String(length=64), nullable=True))
    op.add_column('pipeline_logs', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.create_index('ix_pipeline_logs_entry_url_hash', 'pipeline_logs', ['entry_url_hash'], unique=False)
    op.create_index('ix_pipeline_logs_trace_id', 'pipeline_logs', ['trace_id'], unique=False)
    op.drop_index(op.f('prompts_name_null_model_idx'), table_name='prompts', postgresql_where='(model IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('prompts_name_null_model_idx'), 'prompts', ['name'], unique=True, postgresql_where='(model IS NULL)')
    op.drop_index('ix_pipeline_logs_trace_id', table_name='pipeline_logs')
    op.drop_index('ix_pipeline_logs_entry_url_hash', table_name='pipeline_logs')
    op.drop_column('pipeline_logs', 'retry_count')
    op.drop_column('pipeline_logs', 'failure_reason')
    op.drop_column('pipeline_logs', 'entry_url_hash')
    op.drop_column('pipeline_logs', 'entry_url')
    op.drop_column('pipeline_logs', 'trace_id')
    op.drop_index(op.f('ix_pipeline_run_summaries_trace_id'), table_name='pipeline_run_summaries')
    op.drop_index('ix_pipeline_run_summaries_status', table_name='pipeline_run_summaries')
    op.drop_index('ix_pipeline_run_summaries_finished_at', table_name='pipeline_run_summaries')
    op.drop_table('pipeline_run_summaries')
    # ### end Alembic commands ###
