"""add neutralization_status to story_neutralized

Revision ID: b29c9075587e
Revises: 53b582a6786a
Create Date: 2026-01-26 16:50:13.249534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29c9075587e'
down_revision: Union[str, Sequence[str], None] = '53b582a6786a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add neutralization_status with server_default so existing rows get 'success'
    op.add_column('stories_neutralized', sa.Column(
        'neutralization_status',
        sa.String(length=50),
        nullable=False,
        server_default='success'
    ))
    op.add_column('stories_neutralized', sa.Column('failure_reason', sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories_neutralized', 'failure_reason')
    op.drop_column('stories_neutralized', 'neutralization_status')
    # ### end Alembic commands ###
